spring.application.name=student-course-registration
#                               PORT
server.port=8081
#                               DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/student_course_registration
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jackson.deserialization.fail-on-unknown-properties=true

#                               SECURITY
jwt.secret=7l7m5T0vR9cN2xQa8pLs6YwEe4Kb1HvZu3Df9AjMx8Rn5Gc
jwt.expiration=86400000




