spring.application.name=student-course-registration
spring.security.user.name=admin
spring.security.user.password=$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy
spring.datasource.url=jdbc:postgresql://localhost:5432/student_course_registration
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8081

spring.jackson.deserialization.fail-on-unknown-properties=true
